In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df=pd.read_csv("/content/ev_car_India_dataset.csv")

In [4]:
print(df.head())

      Brand          Model  Price  Range  Power  Battery
0    Maruti  SuzukieVitara  15.99  440.0  142.0     49.0
1      Tata        PunchEV   9.69  275.0   87.0     30.0
2  Mahindra          XEV9e  21.90  542.0  228.0     59.0
3  Mahindra            BE6  18.90  557.0  228.0     59.0
4        MG      WindsorEV  14.00  332.0  134.0     38.0

In [5]:
print(df.shape)

(26, 6)

In [6]:
print(df.dtypes)

Brand       object
Model       object
Price      float64
Range      float64
Power      float64
Battery    float64
dtype: object

In [7]:
df.describe()

           Price       Range       Power    Battery
count  26.000000   26.000000   26.000000  26.000000
mean   28.770000  443.423077  191.531154  52.677692
std    21.781663  121.837654  102.742266  20.775912
min     3.250000  175.000000   16.000000  12.600000
25%    15.615000  388.750000  136.000000  39.000000
50%    18.460000  468.000000  174.330000  54.650000
75%    40.747500  536.250000  233.250000  66.050000
max    75.000000  663.000000  503.000000  90.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    26 non-null     object
 1   Model    26 non-null     object
 2   Price    26 non-null     float64
 3   Range    26 non-null     float64
 4   Power    26 non-null     float64
 5   Battery  26 non-null     float64
dtypes: float64(4), object(2)
memory usage: 1.3+ KB

In [9]:
df.isnull().sum()

Brand      0
Model      0
Price      0
Range      0
Power      0
Battery    0
dtype: int64

In [10]:
df["Model"].unique()

array(['SuzukieVitara', 'PunchEV', 'XEV9e', 'BE6', 'WindsorEV', 'CometEV',
       'Cyberster', 'NexonEV', 'HarrierEV', 'TiagoEV', 'CretaElectric',
       'MobilityEva', 'EV6', 'ZSEV', 'VF7', 'CurvvEV', 'VF6', 'M9',
       'Sealion7', 'Seal', 'iX1', 'EX30', 'Atto3', 'XUV400EV', 'i4',
       'UrbanCruiserEBELLA'], dtype=object)

In [21]:
X=df.drop("Price", axis=1)
y=df["Price"]

In [12]:
categorical=["Brand", "Model"]
numerical=["Range", "Power", "Battery"]

In [13]:
preprocessor= ColumnTransformer([
    ("Categorical",
     OneHotEncoder(handle_unknown="ignore"),
     categorical),

    ("Numerical",
     StandardScaler(),
     numerical)
])

In [22]:
X_train, X_test, y_train, y_test= train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
from sklearn import preprocessing
alphas=[0.01, 0.1, 1, 10, 100]
results=[]
for alpha in alphas:
  model=Pipeline([
      ("Preprocessing", preprocessor),
      ("Ridge", Ridge(alpha=alpha))
  ])
  model.fit(X_train, y_train)

In [24]:
train_pred=model.predict(X_train)
test_pred=model.predict(X_test)

In [19]:
train_mae=mean_absolute_error(y_train, train_pred)
train_rmse=np.sqrt(mean_squared_error(y_train, train_pred))
train_r2=r2_score(y_train, train_pred)

In [25]:
test_mae=mean_absolute_error(y_test, test_pred)
test_rmse=np.sqrt(mean_squared_error(y_test, test_pred))
test_r2=r2_score(y_test, test_pred)

In [26]:
results.append([alpha, train_mae, train_rmse, train_r2, test_mae, test_rmse, test_r2])

In [27]:
print(results)

[[100, 13.00417592430386, np.float64(14.996609391680673), 0.46828394675565943, 16.214627227800246, np.float64(18.564924205557084), 0.34342687977994]]

In [28]:
results=pd.DataFrame(
    results,
    columns=[
        "Alpha",
        "Train MAE",
        "Train RMSE",
        "Train R2",
        "Test MAE",
        "Test RMSE",
        "Test R2"
      ]
    )

In [29]:
print("\nRidge Regression Results:")
print(results)

Ridge Regression Results:
   Alpha  Train MAE  Train RMSE  Train R2   Test MAE  Test RMSE   Test R2
0    100  13.004176   14.996609  0.468284  16.214627  18.564924  0.343427